### PR TITLE
More support for argument buffers

### PR DESCRIPTION
**Pull request by alexbool**

### CODE REVIEW

**Comment by kvark** [comment]
Bors r+

**Comment by kvark** [comment]
Jeez, Travis, don't die!
bors r+

**Comment by kvark** [comment]
Bors r+

**Comment by kvark** [comment]
Bors r+

**Comment by kvark** [comment]
Maaan
Bors r+

**Comment by kvark** [comment]
Bors r+

**Comment by kvark** [comment]
Bors r+

**Comment by kvark** [comment]
Bors r+

**Comment by kvark** [comment]
Bors r+

**Comment by kvark** [comment]
Bors r+

**Comment by kvark** [comment]
No freaking way, looks like Travis is back!!!!

**Comment by alexbool** [comment]
Whoa, that was hard!
@kvark could you make a release on crates.io with this PR please?

**Comment by kvark** [comment]
Sure, will do later today.

**Comment by kvark** [comment]
@alexbool https://crates.io/crates/metal-rs/0.6.3

**Pull request merged**
