### PR TITLE
More pixel formats

### PR DESCRIPTION
**Pull request by kvark**
r? @grovesNL 
Note: as with previous PR, this is technically a breaking change, since we are extending an enum. However, we don't expect anyone to it exhaustively. If any complaints come, we'll yank it in no time.

### CODE REVIEW

**Comment by grovesNL** [comment]
From quickly glancing through it we could also add

```
R8Unorm_sRGB = 11,
RG8Unorm_sRGB = 31,
```

or we can update in a later PR

**Comment by kvark** [comment]
Nicely spotted! PTAL

**Comment by kvark** [comment]
Bors delegate=grovesNL

**Comment by grovesNL** [comment]
👍 
bors r+

**Pull request merged**
