### PR TITLE
Copy texture to texture

### PR DESCRIPTION
**Pull request by kvark**

### CODE REVIEW

**Comment by kvark** [comment]
@grovesNL jeez, I'm being super sloppy. Thanks for noticing this! PTAL

**Comment by kvark** [comment]
I believe it's good now :crossed_fingers: 
bors r=grovesNL

**Comment by grovesNL** [comment]
It was worth trying 😄 you should be able to merge now at least

**Comment by kvark** [comment]
@grovesNL sorry about that! Please try again

**Pull request merged**
