### PR TITLE
Continue compute support

### PR DESCRIPTION
**Pull request by grovesNL**
- Manually merged changes from #17 because of the file rename and addressed review comments
- Added some more bindings necessary to support simple compute
- Added a simple compute example

I'm not sure I have all the details of the example correct (although it seems to work fine), so any feedback would be great.

### CODE REVIEW

**Comment by kvark** [comment]
Thank you for resurrecting this PR! I don't have any complains about the code, but could you properly assign the authorship of the first commit to @burtonageo? If you did a fetch + cherry-pick, it would be done automatically.

**Comment by grovesNL** [comment]
I originally tried to fetch + cherry-pick but was having some issues with a merge conflict (a file was moved/renamed, but there are later commits to the original file location on `master`). I agree that we should keep the original authorship if possible though. I'll keep trying.

**Comment by kvark** [comment]
@grovesNL I'd try the following:
```bash
git rebase -i HEAD^^^^
// mark the first commit as "edit"
git commit --author "<original_author"
git rebase --continue
```

**Comment by grovesNL** [comment]
Alright I did it more incrementally this time around 😄 that seemed to work. Should I squash both sets of commits too?

**Comment by kvark** [comment]
Please do squash a bit, yeah. I guess the last commit (about the example) can stay separate.

**Comment by kvark** [comment]
Oops, I meant:
bors delegate=grovesNL

**Pull request merged**
