### PR TITLE
Remove unreachable code

### PR DESCRIPTION
**Pull request by AlexanderEkdahl**
Not sure what exactly changed (Rust version?, dependency version?) since I haven't seen this when working on this codebase earlier.

### CODE REVIEW

**Comment by madsmtm** [comment]
This only works on `aarch64`, on `x86_64` the `YES` and `NO` constants are different.

**Comment by AlexanderEkdahl** [comment]
> This only works on `aarch64`, on `x86_64` the `YES` and `NO` constants are different.

Oh I see. Thank you for the insight. 

I'm trying to think of other workarounds to remove the linter noise.

**Comment by AlexanderEkdahl** [comment]
One possible workaround is of course something like the following:

``` rust
match msg_send![self, isFramebufferOnly] {
    YES => true,
    NO => false,
    #[cfg(not(target_arch = "aarch64"))]
    _ => unreachable!(),
}
```

**Comment by fornwall** [comment]
> One possible workaround is of course something like the following:
> 
> ```rust
> match msg_send![self, isFramebufferOnly] {
>     YES => true,
>     NO => false,
>     #[cfg(not(target_arch = "aarch64"))]
>     _ => unreachable!(),
> }
> ```

Proposed that in #273.

**Comment by AlexanderEkdahl** [comment]
Thank you @fornwall

**Pull request closed without merging**
