### PR TITLE
add `presented_time` to `Drawable` 

### PR DESCRIPTION
**Pull request by marcpabst**
https://developer.apple.com/documentation/metal/mtldrawable/2806855-presentedtime

In preparation for https://github.com/gfx-rs/wgpu/issues/2869.

### CODE REVIEW

**Comment by MarijnS95** [comment]
Good to mention that this PR depends on #298, which should be (squash-)merged first.

**Comment by Jasper-Bekkers** [comment]
And probably a nice idea to attribute the PR to the original author (@FlannyH)

**Comment by marcpabst** [comment]
Yep - sorry! Never submitted a PR that supersedes another one and was under the impression that GitHub keeps track of that automatically.

**Comment by MarijnS95** [comment]
@marcpabst no worries! GitHub doesn't have any support for this at all, so a little hint in the PR description is the least one can do (there's a finicky trick with target branches but it doesn't work across forks and is _super_ fragile).

Note also that you don't need to create a PR on your local fork to incorporate another change as a base - pro-tip for next time :+1:

**Comment by grovesNL** [comment]
Just rebasing this, will merge in a minute

**Pull request closed without merging**
