### PR TITLE
use autoreleasepool in examples/window. otherwise, if the window is m…

### PR DESCRIPTION
**Pull request by adamnemecek**
…inimzed, the memory used grows unboundedly

### CODE REVIEW

**Review by kvark — APPROVED** [review]

**Review by grovesNL — APPROVED** [review]
bors r+

**Comment by grovesNL** [comment]
bors retry

**Comment by grovesNL** [comment]
bors retry

**Comment by grovesNL** [comment]
@kvark looks like the [status names in bors.toml](https://github.com/gfx-rs/metal-rs/blob/master/bors.toml#L1) needs to be updated. Do we want to keep using bors here?

**Pull request merged**
